server:
  port: 8083
  name: cards

spring:
  application:
    name: cards
  profiles:
    active: prod
  datasource:
    hikari:
      connection-timeout: ${DATASOURCE_CONNECTION_TIMEOUT:20000}
      maximum-pool-size: ${DATASOURCE_MAX_POOL_SIZE:5}

    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/cardsdb}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: "optional:configserver:http://localhost:9091/"

management:
  endpoints:
    enable-by-default: false
    web:
      exposure:
        include: "health, metrics, info"
  endpoint:
    health:
      enable: true
      show-details: always
    metrics:
      enable: true
    info:
      env:
        enable: true
    shutdown:
      access: unrestricted

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Wolf Cards Accounts Microservice"
    version: "1.1.0"

logging:
  level:
    com:
      bank:
        accounts: DEBUG