CREATE TABLE IF NOT EXISTS card (
                                    card_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    mobile_number VARCHAR(15) NOT NULL,
    card_number VARCHAR(100) NOT NULL,
    card_type VARCHAR(100) NOT NULL,
    total_limit INTEGER NOT NULL,
    amount_used INTEGER NOT NULL,
    available_amount INTEGER NOT NULL,
    created_at DATE NOT NULL,
    created_by VARCHAR(20) NOT NULL,
    updated_at DATE DEFAULT NULL,
    updated_by VARCHAR(20) DEFAULT NULL
    );